version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: hospital_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: hospital_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"


volumes:
  db-data:
